name: Playwright Tests

on:
  workflow_dispatch:

  repository_dispatch:
    types: [run-playwright-tests]

  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright Browsers
      run: playwright install

    - name: Run Tests
      id: runtests
      shell: pwsh
      continue-on-error: true
      run: |
        $suite = "${{ github.event.client_payload.suite }}"

        if ([string]::IsNullOrWhiteSpace($suite)) {
          $suite = "Smoke"
        }

        Write-Host "Running suite: $suite"

        dotnet test --filter "Category=$suite"

        if ($LASTEXITCODE -eq 0) {
          echo "test_result=success" >> $env:GITHUB_OUTPUT
        }
        else {
          echo "test_result=failure" >> $env:GITHUB_OUTPUT
        }

    - name: Move Jira Ticket to DONE
      if: steps.runtests.outputs.test_result == 'success'
      shell: pwsh
      run: |
        $body = @{
          transition = @{
            id = "31"
          }
        } | ConvertTo-Json

        Invoke-RestMethod `
          -Uri "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.issueKey }}/transitions" `
          -Method Post `
          -Headers @{
            Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}"))
            Accept = "application/json"
          } `
          -ContentType "application/json" `
          -Body $body

    - name: Move Jira Ticket to FALLIDO
      if: steps.runtests.outputs.test_result == 'failure'
      shell: pwsh
      run: |
        $body = @{
          transition = @{
            id = "2"
          }
        } | ConvertTo-Json

        Invoke-RestMethod `
          -Uri "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.issueKey }}/transitions" `
          -Method Post `
          -Headers @{
            Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}"))
            Accept = "application/json"
          } `
          -ContentType "application/json" `
          -Body $body

        - name: Add Comment to Jira Ticket
              if: always()
              shell: pwsh
              run: |

                $testResult = "${{ steps.runtests.outputs.test_result }}"
                $suite = "${{ github.event.client_payload.suite }}"
                $issueKey = "${{ github.event.client_payload.issueKey }}"

                $allureUrl = "https://testgroupjira.github.io/SauceDemoPlaywright/"
                $workflowUrl = "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

                $comment = @"
                {
                  "body": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                      {
                        "type": "paragraph",
                        "content": [
                          {
                            "type": "text",
                            "text": "Resultado ejecución Playwright: $testResult"
                          }
                        ]
                      },
                      {
                        "type": "paragraph",
                        "content": [
                          {
                            "type": "text",
                            "text": "Suite ejecutada: $suite"
                          }
                        ]
                      },
                      {
                        "type": "paragraph",
                        "content": [
                          {
                            "type": "text",
                            "text": "Allure Report: "
                          },
                          {
                            "type": "text",
                            "text": "$allureUrl",
                            "marks": [
                              {
                                "type": "link",
                                "attrs": {
                                  "href": "$allureUrl"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "type": "paragraph",
                        "content": [
                          {
                            "type": "text",
                            "text": "GitHub Workflow: "
                          },
                          {
                            "type": "text",
                            "text": "$workflowUrl",
                            "marks": [
                              {
                                "type": "link",
                                "attrs": {
                                  "href": "$workflowUrl"
                                }
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
        "@

        Invoke-RestMethod `
          -Uri "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/$issueKey/comment" `
          -Method Post `
          -Headers @{
            Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}"))
            Accept = "application/json"
          } `
          -ContentType "application/json" `
          -Body $comment

    - name: Install Allure
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          TestResults
          allure-results

    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report