name: Playwright Tests

on:
  workflow_dispatch:

  repository_dispatch:
    types: [run-playwright-tests]

  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright Browsers
      run: playwright install

    - name: Run Tests
      run: dotnet test --filter "Category=${{ github.event.client_payload.suite }}"

    - name: Install Allure
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          TestResults
          allure-results